import React from 'react';

const TermsPage: React.FC = () => {
  return (
    <div className="animate-fade-in py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-slate-300 space-y-8">
        <header className="text-center">
            <h1 className="text-4xl md:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-indigo-600">
                Terms and Conditions
            </h1>
            <p className="mt-4 text-slate-500">
                Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
        </header>

        <div className="space-y-6 text-slate-400 leading-relaxed p-8 bg-slate-800/50 rounded-xl border border-slate-700">
          <p>
            Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the VEO Superprompt Generator website (the "Service") operated by us. Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
          </p>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-2">2. Use of Service</h2>
            <p>
              The VEO Superprompt Generator is provided for your personal and commercial use. You agree not to use the service for any illegal or unauthorized purpose. You are responsible for any content you generate and its compliance with applicable laws. We are not responsible for the output generated by the AI models or how you choose to use it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-2">3. API Usage</h2>
            <p>
              The Service utilizes the Google Gemini API. Your use of the Service is also subject to Google's API Terms of Service. You are responsible for providing your own API key for use on your local machine, and you are responsible for any costs associated with its use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-2">4. Intellectual Property</h2>
            <p>
              The Service and its original content (excluding content generated by users), features, and functionality are and will remain the exclusive property of VEO Superprompt Generator and its licensors. You retain all rights to the prompts you create and the content generated from them, subject to the terms of the underlying AI model provider.
            </p>
          </section>
          
          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-2">5. Limitation of Liability</h2>
            <p>
              In no event shall VEO Superprompt Generator, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
          </section>
          
          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-2">6. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms and Conditions on this page. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms and Conditions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-2">7. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us through the information provided on our Contact page.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
